version: "3.8"
services:
  mysql:
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "./docker_server/mysql/data:/var/lib/mysql"
      - "./docker_server/mysql/conf:/etc/mysql/conf.d"
#  redis:
#    image: redis:5.0.9
#    ports:
#      - "6379:6379"
#    environment:
#      - TZ=Asia/Shanghai
#      - LANG=en_US.UTF-8
#    volumes:
#      - "./server/redis/config/redis.conf:/usr/local/etc/redis/redis.conf"
#      - "./docker_server/redis/data/:/data/"